-- 重建用：依相依倒序 DROP
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'ANSWER_OPTIONS','ANSWERS','RESPONSES','QUESTION_RULES','QUESTION_OPTIONS',
        'QUESTIONS','FORM_PAGES','FORM_AUDIENCES','FORMS','LOGIN_ATTEMPTS','AUDIT_LOGS','USERS'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/
